### ISSUE TITLE
Default PORT to telnet and ssh.

### ISSUE THREAD

**Issue by danielsoro** [tomitribe/sheldon#2]
public SshdServer(ConsoleSession session, String domain) {
        this.session = session;
        this.domain = domain;
        this.port = DEFAULT_PORT_SSH; // 22
}

public TelnetServer(ConsoleSession session) {
        this.session = session;
        this.port = DEFAULT_PORT_TELNET; // 23
}

WDYT?

**Comment by jgallimore** [comment]
I like the idea, but am hesitant, as this might conflict with ssh/telnet daemons installed on Linux servers, and would also require TomEE to run a privileged user because these ports are <1024. The port setting can be changed in ra.xml or via system.properties - how about I include details on how to do that on the README.md? What do you think?

Regards

Jon

**Comment by danielsoro** [comment]
Sorry, I didn't see your message.
Not merge my PR.

**Comment by danielsoro** [comment]
Yeah!
I understood your preoccupation.
Please, add in README. 

Thanks Jon! :)

**Comment by danielsoro** [comment]
See: https://github.com/tomitribe/telnet-connector/issues/7
